"""
ONNX parity test: PyTorch logits ≈ ONNX logits within epsilon.

Requires:
    ml/output/model.onnx  (generated by export_onnx.py)
    ml/output/model.pt    (generated by train.py)

Skipped automatically if artifacts are not present (e.g., fresh CI without LFS).
"""
import os
import sys

import numpy as np
import pytest

# Skip entire module if torch or onnxruntime are not installed
torch = pytest.importorskip("torch", reason="torch not installed — skipping parity tests")
pytest.importorskip("onnxruntime", reason="onnxruntime not installed — skipping parity tests")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "output")
MODEL_PT = os.path.join(OUTPUT_DIR, "model.pt")
MODEL_ONNX = os.path.join(OUTPUT_DIR, "model.onnx")

ONNX_AVAILABLE = os.path.isfile(MODEL_ONNX)
PT_AVAILABLE = os.path.isfile(MODEL_PT)
SKIP_REASON = "model.onnx or model.pt not found — run train.py and export_onnx.py first"


@pytest.mark.skipif(not (ONNX_AVAILABLE and PT_AVAILABLE), reason=SKIP_REASON)
class TestOnnxParity:
    EPSILON = 1e-4
    BATCH_SIZE = 8

    @pytest.fixture(scope="class")
    def pytorch_model(self):
        from models import DigitCNN

        model = DigitCNN()
        model.load_state_dict(torch.load(MODEL_PT, map_location="cpu"))
        model.eval()
        return model

    @pytest.fixture(scope="class")
    def onnx_session(self):
        import onnxruntime as ort

        sess = ort.InferenceSession(MODEL_ONNX, providers=["CPUExecutionProvider"])
        return sess

    @pytest.fixture(scope="class")
    def fixed_input(self):
        torch.manual_seed(0)
        return torch.randn(self.BATCH_SIZE, 1, 28, 28, dtype=torch.float32)

    def test_logits_close(self, pytorch_model, onnx_session, fixed_input):
        with torch.no_grad():
            pt_logits = pytorch_model(fixed_input).numpy()

        ort_inputs = {onnx_session.get_inputs()[0].name: fixed_input.numpy()}
        onnx_logits = onnx_session.run(None, ort_inputs)[0]

        max_diff = np.abs(pt_logits - onnx_logits).max()
        assert max_diff < self.EPSILON, (
            f"Max logit difference {max_diff:.6f} exceeds epsilon {self.EPSILON}.\n"
            f"PyTorch logits[0]: {pt_logits[0]}\n"
            f"ONNX    logits[0]: {onnx_logits[0]}"
        )

    def test_predictions_match(self, pytorch_model, onnx_session, fixed_input):
        """Predicted class must be identical for all inputs in the batch."""
        with torch.no_grad():
            pt_preds = pytorch_model(fixed_input).argmax(dim=1).numpy()

        ort_inputs = {onnx_session.get_inputs()[0].name: fixed_input.numpy()}
        onnx_preds = onnx_session.run(None, ort_inputs)[0].argmax(axis=1)

        np.testing.assert_array_equal(
            pt_preds, onnx_preds,
            err_msg="PyTorch and ONNX predictions differ on at least one input"
        )

    def test_onnx_output_shape(self, onnx_session, fixed_input):
        ort_inputs = {onnx_session.get_inputs()[0].name: fixed_input.numpy()}
        output = onnx_session.run(None, ort_inputs)[0]
        assert output.shape == (self.BATCH_SIZE, 10), (
            f"Expected ({self.BATCH_SIZE}, 10), got {output.shape}"
        )

    def test_single_sample_inference(self, pytorch_model, onnx_session):
        """Verify single-sample (batch=1) inference works."""
        torch.manual_seed(99)
        x = torch.randn(1, 1, 28, 28, dtype=torch.float32)

        with torch.no_grad():
            pt_logits = pytorch_model(x).numpy()

        ort_inputs = {onnx_session.get_inputs()[0].name: x.numpy()}
        onnx_logits = onnx_session.run(None, ort_inputs)[0]

        max_diff = np.abs(pt_logits - onnx_logits).max()
        assert max_diff < self.EPSILON
